### ISSUE TITLE
Goal: TSN Stream Standard

### ISSUE THREAD

**Issue by zolotokrylin** [trufnetwork/node#137]
# [Specs](https://docs.google.com/document/d/1jHVVHjobZtTyOplySYXiSzpV8SQSHWom6FUHcHEZGSU/edit)
Everyone is welcome to ask questions and suggest ideas in the document (use "suggestion mode")

### Blocked by
- truflation/tsn#114 
- https://github.com/truflation/tsn/issues/269
- truflation/tsn#221
- truflation/tsn#222
- https://github.com/truflation/tsn/issues/302
- https://github.com/truflation/truflation-transformers/issues/80
- https://github.com/truflation/tsn-data-provider/issues/125
- https://github.com/truflation/tsn-data-provider/issues/133
- https://github.com/truflation/tsn/issues/319
- https://github.com/truflation/tsn/issues/326
- https://github.com/truflation/tsn/issues/337

### Kwil Tasks
- [x] truflation/tsn#221
- [x] truflation/tsn#222
- [x] https://github.com/truflation/tsn/issues/257
- [x] https://github.com/truflation/tsn/issues/292
- [x] https://github.com/truflation/tsn/issues/296
- [x] https://github.com/truflation/tsn/issues/302
- [x] https://github.com/truflation/tsn/issues/330

### TSN tasks

- [x] truflation/tsn#224
- [x] truflation/tsn#225
- [x] truflation/tsn#226
- [x] truflation/tsn#227
- [x] https://github.com/truflation/tsn/issues/300
---
- [x] truflation/tsn#228
- [x] truflation/tsn#229
- [x] truflation/tsn#230
- [x] truflation/tsn#231
- [x] truflation/tsn#232
- [x] truflation/tsn#267
- [x] truflation/tsn#297
- [x] https://github.com/truflation/tsn/issues/314
---
- [x] truflation/tsn#233
- [x] truflation/tsn#234
- [x] truflation/tsn#235
- [x] truflation/tsn#236
- [x] truflation/tsn#237
- [x] https://github.com/truflation/tsn/issues/283
- [x] truflation/tsn#238
- [x] https://github.com/truflation/tsn/issues/291
---
- [x] truflation/tsn#239
- [x] truflation/tsn#240
- [x] truflation/tsn#288
- [x] truflation/tsn#241
- [x] https://github.com/truflation/tsn/issues/217
- [x] https://github.com/truflation/tsn/issues/218
- [x] https://github.com/truflation/tsn/issues/219
- [x] truflation/tsn#242
- [x] truflation/tsn#251 
- [x] truflation/tsn#252
---
- [x] https://github.com/truflation/tsn/issues/309 (Not a blocker for deployment)
- [x] truflation/tsn#271
- [x] https://github.com/truflation/tsn-data-provider/issues/120
- [x] https://github.com/truflation/tsn-data-provider/issues/125
- [x] https://github.com/truflation/tsn/issues/338

### Truflation Data Provider Tasks
- [x] truflation/tsn-data-provider#95
- [x] truflation/tsn-data-provider#94
- [x] truflation/tsn-data-provider#93
- [x] truflation/tsn-data-provider#92
- [x] truflation/tsn-data-provider#91
- [x] https://github.com/truflation/tsn-data-provider/issues/97
- [x] https://github.com/truflation/tsn-data-provider/issues/89
- [x] https://github.com/truflation/tsn-data-provider/issues/101
- [x] https://github.com/truflation/tsn-data-provider/issues/102
- [x] https://github.com/truflation/tsn-data-provider/issues/103
- [x] https://github.com/truflation/tsn-data-provider/issues/110
- [x] https://github.com/truflation/tsn-data-provider/issues/111
- [x] truflation/tsn-data-provider#116
- [x] https://github.com/truflation/tsn-data-provider/issues/118
- [x] https://github.com/truflation/truflation-transformers/issues/80
- [x] https://github.com/truflation/tsn-data-provider/issues/127
- [x] https://github.com/truflation/tsn/issues/324
- [x] https://github.com/truflation/tsn/issues/325
- [x] https://github.com/truflation/tsn/issues/320
- [x] https://github.com/truflation/tsn-data-provider/issues/141

## EV
- [x] https://github.com/truflation/tsn-data-provider/issues/139

---
- [x] https://github.com/truflation/tsn/issues/287
- [x] https://github.com/truflation/tsn/issues/321
