### ISSUE TITLE
Goal: Billing

### ISSUE THREAD

**Issue by zolotokrylin** [trufnetwork/node#166]
# [Specs](https://docs.google.com/document/d/1U5TWFGpis2-UsK1hnj23xFyZChJBWG90jBr52cSCc_M)
---

# Blocker
- https://github.com/truflation/tsn/issues/403
- https://github.com/truflation/website/issues/5

# Related
- https://github.com/truflation/tsn/issues/383
- https://github.com/truflation/website/issues/577

# Problems

## To decide
- ~Problem: truflation/tsn-synchronizer repo is not created~ (cancelled)

## Billing/Data provider tasks
- [x] truflation/tsn-data-provider#144
- [x] truflation/tsn-data-provider#145
- [x] truflation/tsn-data-provider#146
- [x] truflation/tsn-data-provider#147
- [x] truflation/tsn-data-provider#148
- [x] truflation/tsn-data-provider#149
- [x] https://github.com/truflation/tsn-data-provider/issues/171
- [x] truflation/tsn-data-provider#150
- [x] truflation/tsn-data-provider#151
- [x] https://github.com/truflation/tsn-data-provider/issues/174
- [x] truflation/tsn-data-provider#152
- [x] truflation/tsn-data-provider#153
- [x] truflation/tsn-data-provider#154
- [x] truflation/tsn-data-provider#158
- [x] truflation/tsn-data-provider#159
- [x] truflation/tsn-data-provider#155
- [x] truflation/tsn-data-provider#156
- [x] truflation/tsn-data-provider#157
- [x] truflation/tsn-data-provider#179
- [x] https://github.com/truflation/tsn-data-provider/issues/185
- [x] https://github.com/truflation/tsn-data-provider/issues/187
- [x] https://github.com/truflation/tsn-data-provider/issues/189
- [x] https://github.com/truflation/tsn-data-provider/issues/191
- [x] https://github.com/truflation/tsn-data-provider/issues/194
- [x] https://github.com/truflation/tsn-data-provider/issues/205

## TSN Tasks
- [x] https://github.com/truflation/tsn/issues/401
- [x] https://github.com/truflation/tsn/issues/399
- [x] https://github.com/truflation/tsn/issues/409
- [x] https://github.com/truflation/tsn/issues/411
- [x] https://github.com/truflation/tsn/issues/413
- [x] https://github.com/truflation/tsn/issues/429

## Supabase tasks
- [x] truflation/website#426
- [x] truflation/website#480
- [x] truflation/website#481
- [x] truflation/website#436

## Website tasks
- [x] https://github.com/truflation/website/issues/497
- [x] truflation/website#553
- [x] https://github.com/truflation/website/issues/568
