### ISSUE TITLE
Goal: Prepare TSN SDK for Koii <> Truflation Hackathon

### ISSUE THREAD

**Issue by outerlook** [trufnetwork/node#348]
# [Planning Document](https://docs.google.com/document/d/1AlnVECF-ek5hUsTQ4VrZySXhUTrpj9uEVwHu2Mc-9Sw/edit?usp=sharing)

Hackathon Overview

> Truflation and Koi are excited to announce a collaborative hackathon aimed at harnessing the power of web crawlers to enhance Truflation's suite of index tools. Participants will have the opportunity to earn Truflation tokens (TRUF), Koi tokens (KOII), and cash prizes in USDC by developing innovative solutions that support true election data aggregation and analysis. This hackathon emphasizes the integration of multiple data feeds, standardization of data formats, and advanced sentiment and statistical analysis.

- move current logic to interact with TSN **as is**, in which users:
	- deploy/destroy contracts
	- modify important metadata (permissions, etc)
	- insert data
	- read data
- create simple tests, that will also demonstrate how it works
- create documentation of important aspects to the public (create streams, publish data, compose streams, read from all)
- try to improve the logic AS IS to something more aligned to other SDK's DX
- Low Priority: Include Truflation TSN Contracts purely as examples demonstrating that contracts can be modified as long as the interface remains the same
- Low Priority: Typescript SDK?

### Tasks

- [x] #349
- [x] #355
- [x] #360
- [x] #361
- [ ] Problem(tsn-sdk): SDK has a weird DX
- [ ] Problem(tsn-sdk): Include Truflation contracts example and docs about its modifications
- [ ] Problem(tsn-sdk): Typescript SDK

### Blockers
- [x] https://github.com/truflation/tsn/issues/356
