### ISSUE TITLE
Goal: fix domains hierarchy structure

### ISSUE THREAD

**Issue by zolotokrylin** [trufnetwork/node#446]
> We might want a shared configuration file for our chain data, correct? As @truflation/team-tsn-kwil is the expert on the configuration, please let me know if sharing a list of node addresses and attaching a subdomain to them is enough for us to connect. E.g. `node-0.tsn.staging.test.truflation.com`

_Originally posted by @outerlook in https://github.com/truflation/tsn/issues/393#issuecomment-2271087740_

## Tasks

- [x] Problem: missing NS records for `tsn.truflation.com`
- [x] truflation/tsn#478
- [x] truflation/tsn#480
- [x] truflation/website#634
- [x] truflation/tsn#482
- [x] truflation/tsn#484
- [x] truflation/tsn-data-provider#215
- [x] truflation/tsn#483
- [x] truflation/tsn-utils#15
- [x] truflation/tsn-utils#16
- [x] #489
- [x] #491
- [x] #490
