### ISSUE TITLE
Goal: get TN data to EVM chains

### ISSUE THREAD

**Issue by markholdex** [trufnetwork/node#547]
# [Specs](https://docs.google.com/document/d/11RFE6YhivcCwkZfj95wO9FV61vym7VBUkwbsYvuSm4Q/edit?usp=sharing)

# Blocking
- https://github.com/truflation/tsn/issues/547

# Related
- https://github.com/truflation/tsn/issues/444

# Problem:
- [x] trufnetwork/truf-data-provider#337
- [x] trufnetwork/node#752
- [x] truflation/tsn#721
- [x] truflation/tsn-data-provider#320
- [x] truflation/tsn-data-provider#321
- [x] truflation/tsn-data-provider#330
- [x] truflation/tsn-data-provider#331
- [x] truflation/tsn-data-provider#332
- [x] trufnetwork/truf-data-provider#347
- [x] #756
- [x] #757

# RnD:
- [x] truflation/tsn#720
- [x] https://github.com/truflation/tsn/issues/725
- [x] trufnetwork/node#733

**Comment by outerlook** [comment]
(publishing to the goal as I think it might be the expected outcome from here, right?)

- The contract [has been deployed](https://sepolia.etherscan.io/address/0x34c81dd71457084dae8e05e713ff8323a543dc5c#code) on sepolia
- there's an initial, but comprehensive docs [available on how to consume](https://github.com/trufnetwork/evm-contracts/blob/feat/deploy/docs/DeveloperGuide.md#tnoracle)

Can we dettach this issue, as downstream goals will be unblocked?
- https://github.com/trufnetwork/node/issues/758

I think the above issue needs some discussion yet (maybe transform into a goal)
The current state is that our contract is a bit upgradeable so we can iterate during next phases, and I have the roles to control it. But we need to remember not to put values that depends on this data until I may either transfer the roles to someone, or renounce to make it entirely immutable.

**Comment by zolotokrylin** [comment]
@markholdex stakeholders are notified in slack about completion?

**Comment by zolotokrylin** [comment]
make sure the iteration is correct 
![Uploading image.png…]()

**Comment by markholdex** [comment]
> @markholdex stakeholders are notified in slack about completion?

just notified. Thx for reminder.
