### ISSUE TITLE
Goal: every-second stream updates

### ISSUE THREAD

**Issue by markholdex** [trufnetwork/node#767]
# [Specs](https://docs.google.com/document/d/1BAv8Uq8QVFPSjvPMVVC5KDymfMBjMyugEstsh7mN7Bs/edit?tab=t.0)

### [Node](https://github.com/trufnetwork/node)
- [x] trufnetwork/node#770
- [x] trufnetwork/node#774
- [ ] Problem: infrastructure might cannot handle rapid updates
- [x] trufnetwork/node#775

### [Truf-Data-Provider](https://github.com/trufnetwork/truf-data-provider)
- [x] https://github.com/trufnetwork/truf-data-provider/issues/383
- [x] https://github.com/trufnetwork/truf-data-provider/issues/386
- [x] https://github.com/trufnetwork/truf-data-provider/issues/392
- [x] https://github.com/trufnetwork/truf-data-provider/issues/396
- [x] https://github.com/trufnetwork/truf-data-provider/issues/397
- [x] https://github.com/trufnetwork/truf-data-provider/issues/399
- [x] https://github.com/trufnetwork/truf-data-provider/issues/400
- [x] https://github.com/trufnetwork/truf-data-provider/issues/403
- [x] https://github.com/trufnetwork/truf-data-provider/issues/405
- [x] https://github.com/trufnetwork/truf-data-provider/issues/408
- [x] trufnetwork/truf-data-provider#411
- [x] https://github.com/trufnetwork/truf-data-provider/issues/415
- [x] trufnetwork/truf-data-provider#416
- [x] https://github.com/trufnetwork/truf-data-provider/issues/418
- [x] https://github.com/trufnetwork/node/issues/785

### [ADAPTERS](https://github.com/trufnetwork/adapters)
- [x] trufnetwork/adapters#55
- [x] https://github.com/trufnetwork/adapters/issues/58

### [SDK-PY](https://github.com/trufnetwork/sdk-py)
- [x] trufnetwork/sdk-py#5
- [x] trufnetwork/sdk-py#6

### [SDK-GO](https://github.com/trufnetwork/sdk-go)
- [x] https://github.com/trufnetwork/sdk-go/issues/62
- [x] trufnetwork/sdk-go#64
- [x] trufnetwork/sdk-go#70
- [x] trufnetwork/sdk-go#72

### [SDK-JS](https://github.com/trufnetwork/sdk-js)
- [x] https://github.com/trufnetwork/sdk-js/issues/30

## ETA: ~2025-01-17~ ~2025-01-18~ ~2025-01-21~ 2025-01-23

**Comment by markholdex** [comment]
@zolotokrylin @outerlook @MicBun please check the specs document and leave your comments/suggestions there. Let's have a call after that.

**Comment by rsoury** [comment]
@markholdex 
Is this a clone of #199?

Is it just the granularity that we need, or are we shooting for real-time subscription to data streams?

**Comment by zolotokrylin** [comment]
@rsoury granularity.

**Comment by MicBun** [comment]
Log: updated the spec document according tothe  latest call.

**Comment by MicBun** [comment]
Log: I've broken down the spec into smaller problems, feel free to adjust or break it down into smaller parts if needed.

**Comment by markholdex** [comment]
@MicBun what is the ETA of this Goal?

**Comment by MicBun** [comment]
I've updated the issue description with the ETA @markholdex

**Comment by outerlook** [comment]
just to aggregate information about our capacity, based on
- https://github.com/trufnetwork/node/issues/775#issuecomment-2578426724
- https://github.com/trufnetwork/node/issues/774#issuecomment-2573926978

with a frequency of 1 record per 5 minutes, based on experiments, we have:
- to achieve under 5 seconds to fetch[1] (arbitrary QoS), we can handle a composition of ~50 streams [2]
- 500 streams with this frequency take ~5GB of data with data for a year (theoretical)


notes:
[1] fetching 1 month of data. If we fetch 1 day of data, we can handle 30x more streams. It's nearly proportional on the new contract.
[2] only if we use the 0.9 optimizations (easy to apply). Using the current version of contracts we can compose ~15 streams

**Comment by markholdex** [comment]
Hey @MicBun are we on track with this goal?

**Comment by MicBun** [comment]
Hi Mark, unfortunately, I discovered some issues and need to hold back the deployment
- https://github.com/trufnetwork/truf-data-provider/issues/408
- https://github.com/trufnetwork/truf-data-provider/issues/405

I'll still try to finish it on  2025-01-18

**Comment by MicBun** [comment]
Apologies for the further delay. @markholdex 
The push service is deployed but not stable yet. It ran into crashes. I will investigate it and might need 1-2 days to resolve.
- https://github.com/trufnetwork/truf-data-provider/issues/415


Bitcoin data:
![Image](https://github.com/user-attachments/assets/2098ee58-75b2-4c15-9c21-f7613dcbdccb)

**Comment by markholdex** [comment]
@MicBun any updates on the ETA?

**Comment by MicBun** [comment]
Hi @markholdex,

After thorough investigation and debugging, it was found the real issue was the `nonce` error. We need to work around the `nonce` error so it is able to push data as fast as possible without causing much error. The `nonce` error will hopefully be resolved by today (2025-01-22). Tomorrow (2025-01-23), I will begin with the redeployment of the contracts and the push services itself. We can start expecting things to run normally and smoothly on 2024-01-23 by the night.

**Comment by MicBun** [comment]
Although it is not every second, we manage to write to TRUF.network with differences in timestamp for about **30 seconds - 1 minute.**

Bitcoin data
![Image](https://github.com/user-attachments/assets/d158dbad-f040-47c5-8489-2d8c86b81daa)

Examples of timestamp differences
![Image](https://github.com/user-attachments/assets/ead2c835-263f-478f-a290-7d3063d92840)
![Image](https://github.com/user-attachments/assets/1c78dcef-9fd8-493c-b6ef-89103aebd8e0)

Fetching the last record
![Image](https://github.com/user-attachments/assets/726ccbf4-0b1b-4b15-883e-344359777774)
![Image](https://github.com/user-attachments/assets/9c604a83-24e7-4823-a813-0c1a018ffa86)

This issue is still open:
- https://github.com/trufnetwork/truf-data-provider/issues/418

However, I've already made direct tweaks to the server, so it is just waiting for a merge (somehow I can't force merge).

@trufnetwork/team-truf-core
